# Generated by Django 5.2.5 on 2026-03-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['car', '-amount'], name='bids_bid_car_id_802542_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['car', '-created_at'], name='bids_bid_car_id_46a752_idx'),
        ),
    ]
