# Generated by Django 5.2.5 on 2026-02-14 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_initial'),
        ('inventory', '0013_remove_carview_unique_car_user_view_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('closed', 'Closed')], default='scheduled', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['car', '-amount'], name='bids_bid_car_id_802542_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['car', '-created_at'], name='bids_bid_car_id_46a752_idx'),
        ),
        migrations.AddField(
            model_name='auction',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='inventory.car'),
        ),
    ]
