# Generated by Django 5.2.5 on 2025-12-20 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0012_car_sold_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='inventory.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['car'], name='rating_carr_car_id_de0100_idx'), models.Index(fields=['user'], name='rating_carr_user_id_90768d_idx'), models.Index(fields=['car', 'user'], name='rating_carr_car_id_8681fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('car', 'user'), name='unique_car_user_rating'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='carrating_valid_range')],
            },
        ),
    ]
