# Generated by Django 5.2.5 on 2026-03-10 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='carrating',
            index=models.Index(fields=['car'], name='rating_carr_car_id_de0100_idx'),
        ),
        migrations.AddIndex(
            model_name='carrating',
            index=models.Index(fields=['user'], name='rating_carr_user_id_90768d_idx'),
        ),
        migrations.AddIndex(
            model_name='carrating',
            index=models.Index(fields=['car', 'user'], name='rating_carr_car_id_8681fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrating',
            constraint=models.UniqueConstraint(fields=('car', 'user'), name='unique_car_user_rating'),
        ),
        migrations.AddConstraint(
            model_name='carrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='carrating_valid_range'),
        ),
    ]
