# Generated by Django 5.2.5 on 2025-09-13 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='brokerrating',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='brokers.brokerprofile'),
        ),
        migrations.AddField(
            model_name='brokerrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['profile'], name='idx_brokerprofile_profile'),
        ),
        migrations.AddIndex(
            model_name='brokerprofile',
            index=models.Index(fields=['national_id'], name='idx_brokerprofile_national_id'),
        ),
        migrations.AddIndex(
            model_name='brokerrating',
            index=models.Index(fields=['broker'], name='idx_brokerrating_broker'),
        ),
        migrations.AddIndex(
            model_name='brokerrating',
            index=models.Index(fields=['user'], name='idx_brokerrating_user'),
        ),
        migrations.AddIndex(
            model_name='brokerrating',
            index=models.Index(fields=['broker', 'user'], name='idx_brokerrating_broker_user'),
        ),
        migrations.AddConstraint(
            model_name='brokerrating',
            constraint=models.UniqueConstraint(fields=('broker', 'user'), name='unique_broker_user_rating'),
        ),
        migrations.AddConstraint(
            model_name='brokerrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='brokerrating_valid_range'),
        ),
    ]
