# Generated by Django 5.2.5 on 2025-08-07 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokerlisting',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokers.broker'),
        ),
        migrations.AddField(
            model_name='brokerlisting',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.car'),
        ),
    ]
