# Generated by Django 5.2.5 on 2025-08-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_initial'),
        ('inventory', '0004_carmake_alter_car_fuel_type_car_make_ref_carmodel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brokerlisting',
            unique_together={('broker', 'car')},
        ),
    ]
