# Generated by Django 5.2.5 on 2025-09-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='can_post',
            field=models.BooleanField(default=False),
        ),
    ]
