# Generated by Django 5.2.5 on 2026-01-30 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_brokerprofile_can_post'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brokerprofile',
            name='idx_brokerprofile_profile',
        ),
        migrations.RemoveIndex(
            model_name='brokerprofile',
            name='idx_brokerprofile_national_id',
        ),
        migrations.RemoveIndex(
            model_name='brokerrating',
            name='idx_brokerrating_broker',
        ),
        migrations.RemoveIndex(
            model_name='brokerrating',
            name='idx_brokerrating_user',
        ),
        migrations.RemoveIndex(
            model_name='brokerrating',
            name='idx_brokerrating_broker_user',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='can_post',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_brokers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='brokerprofile',
            constraint=models.UniqueConstraint(fields=('profile', 'national_id'), name='unique_broker_national_id_per_profile'),
        ),
    ]
