# Generated by Django 5.2.5 on 2025-08-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_alter_brokerlisting_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='commission_rate',
        ),
        migrations.DeleteModel(
            name='BrokerListing',
        ),
    ]
