# Generated by Django 5.2.5 on 2025-08-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_remove_broker_commission_rate_delete_brokerlisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['name']},
        ),
    ]
