# Generated by Django 5.2.5 on 2025-08-28 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_alter_broker_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['broker'], name='idx_brokerrating_broker'), models.Index(fields=['user'], name='idx_brokerrating_user'), models.Index(fields=['broker', 'user'], name='idx_brokerrating_broker_user')],
                'constraints': [models.UniqueConstraint(fields=('broker', 'user'), name='unique_broker_user_rating'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='brokerrating_valid_range')],
            },
        ),
    ]
