# Generated by Django 5.2.5 on 2026-03-11 07:12

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Car Make',
                'verbose_name_plural': 'Car Makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
            },
        ),
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorite Car',
                'verbose_name_plural': 'Favorite Cars',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10)),
                ('mileage', models.IntegerField(db_index=True)),
                ('fuel_type', models.CharField(choices=[('electric', 'Electric'), ('hybrid', 'Hybrid'), ('petrol', 'Petrol'), ('diesel', 'Diesel')], db_index=True, max_length=20)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('other', 'Other')], db_index=True, default='sedan', max_length=20)),
                ('exterior_color', models.CharField(default='white', max_length=20)),
                ('interior_color', models.CharField(default='white', max_length=20)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('drivetrain', models.CharField(choices=[('fwd', 'Front-Wheel Drive'), ('rwd', 'Rear-Wheel Drive'), ('awd', 'All-Wheel Drive'), ('4wd', 'Four-Wheel Drive')], db_index=True, default='fwd', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=20)),
                ('trim', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('pending_inspection', 'Pending Inspection'), ('under_maintenance', 'Under Maintenance'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='available', max_length=30)),
                ('sale_type', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('auction', 'Auction')], default='fixed_price', max_length=20)),
                ('auction_end', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('priority', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bluetooth', models.BooleanField(default=False)),
                ('heated_seats', models.BooleanField(default=False)),
                ('cd_player', models.BooleanField(default=False)),
                ('power_locks', models.BooleanField(default=False)),
                ('premium_wheels_rims', models.BooleanField(default=False)),
                ('winch', models.BooleanField(default=False)),
                ('alarm_anti_theft', models.BooleanField(default=False)),
                ('cooled_seats', models.BooleanField(default=False)),
                ('keyless_start', models.BooleanField(default=False)),
                ('body_kit', models.BooleanField(default=False)),
                ('navigation_system', models.BooleanField(default=False)),
                ('premium_lights', models.BooleanField(default=False)),
                ('cassette_player', models.BooleanField(default=False)),
                ('fog_lights', models.BooleanField(default=False)),
                ('leather_seats', models.BooleanField(default=False)),
                ('roof_rack', models.BooleanField(default=False)),
                ('dvd_player', models.BooleanField(default=False)),
                ('power_mirrors', models.BooleanField(default=False)),
                ('power_sunroof', models.BooleanField(default=False)),
                ('aux_audio_in', models.BooleanField(default=False)),
                ('brush_guard', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('performance_tyres', models.BooleanField(default=False)),
                ('premium_sound_system', models.BooleanField(default=False)),
                ('heat', models.BooleanField(default=False)),
                ('vhs_player', models.BooleanField(default=False)),
                ('off_road_kit', models.BooleanField(default=False)),
                ('am_fm_radio', models.BooleanField(default=False)),
                ('moonroof', models.BooleanField(default=False)),
                ('racing_seats', models.BooleanField(default=False)),
                ('premium_paint', models.BooleanField(default=False)),
                ('spoiler', models.BooleanField(default=False)),
                ('power_windows', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('climate_control', models.BooleanField(default=False)),
                ('parking_sensors', models.BooleanField(default=False)),
                ('rear_view_camera', models.BooleanField(default=False)),
                ('keyless_entry', models.BooleanField(default=False)),
                ('off_road_tyres', models.BooleanField(default=False)),
                ('satellite_radio', models.BooleanField(default=False)),
                ('power_seats', models.BooleanField(default=False)),
                ('tiptronic_gears', models.BooleanField(default=False)),
                ('dual_exhaust', models.BooleanField(default=False)),
                ('power_steering', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('all_wheel_steering', models.BooleanField(default=False)),
                ('front_airbags', models.BooleanField(default=False)),
                ('side_airbags', models.BooleanField(default=False)),
                ('n2o_system', models.BooleanField(default=False)),
                ('anti_lock_brakes', models.BooleanField(default=False)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='brokers.brokerprofile')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealers.dealerprofile')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['make', 'model', 'year'],
            },
        ),
    ]
