# Generated by Django 5.2.5 on 2026-03-11 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='make_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.carmake'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='inventory.carmake'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='inventory.carmodel'),
        ),
        migrations.AddField(
            model_name='carview',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='inventory.car'),
        ),
        migrations.AddField(
            model_name='carview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritecar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='inventory.car'),
        ),
        migrations.AddField(
            model_name='favoritecar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='carimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('car',), name='unique_featured_image_per_car'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('make', 'name')},
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['verification_status'], name='inventory_c_verific_fedb49_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['created_at'], name='inventory_c_created_d24ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['dealer'], name='inventory_c_dealer__aefb05_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['broker'], name='inventory_c_broker__b30f07_idx'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('broker__isnull', True), ('dealer__isnull', False)), models.Q(('broker__isnull', False), ('dealer__isnull', True)), _connector='OR'), name='exactly_one_of_dealer_or_broker'),
        ),
        migrations.AddIndex(
            model_name='carview',
            index=models.Index(fields=['viewed_at'], name='inventory_c_viewed__50cef9_idx'),
        ),
        migrations.AddIndex(
            model_name='carview',
            index=models.Index(fields=['car', 'viewed_at'], name='inventory_c_car_id_0ca96e_idx'),
        ),
        migrations.AddIndex(
            model_name='carview',
            index=models.Index(fields=['user'], name='inventory_c_user_id_be06e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='carview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('car', 'user'), name='unique_car_user_view'),
        ),
        migrations.AddConstraint(
            model_name='carview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('car', 'ip_address'), name='unique_car_ip_view'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecar',
            unique_together={('user', 'car')},
        ),
    ]
