# Generated by Django 5.2.5 on 2025-09-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('other', 'Other')], db_index=True, default='sedan', max_length=20),
        ),
    ]
