# Generated by Django 5.2.5 on 2025-09-09 07:50

import django.db.models.deletion
import online_car_market.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_carmake_updated_at_remove_carmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['make', 'model', 'year'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('other', 'Other')], db_index=True, default='sedan', max_length=20),
        ),
    ]
