# Generated by Django 5.2.4 on 2025-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_car_images_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('pending_inspection', 'Pending Inspection'), ('under_maintenance', 'Under Maintenance'), ('delivered', 'Delivered'), ('archived', 'Archived')], default='available', max_length=30),
        ),
    ]
