# Generated by Django 5.2.5 on 2025-09-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_car_options_remove_carmake_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bluetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(choices=[('fwd', 'Front-Wheel Drive'), ('rwd', 'Rear-Wheel Drive'), ('awd', 'All-Wheel Drive'), ('4wd', 'Four-Wheel Drive')], db_index=True, default='fwd', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('silver', 'Silver'), ('gray', 'Gray'), ('green', 'Green'), ('yellow', 'Yellow'), ('other', 'Other')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(choices=[('black', 'Black'), ('beige', 'Beige'), ('gray', 'Gray'), ('brown', 'Brown'), ('white', 'White'), ('other', 'Other')], default='white', max_length=20),
        ),
    ]
