# Generated by Django 5.2.5 on 2026-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_car_reviewed_at_car_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='views_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
