# Generated by Django 5.2.5 on 2025-08-27 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_alter_broker_options'),
        ('dealers', '0004_rename_name_dealer_company_name_dealer_phone_and_more'),
        ('inventory', '0005_alter_car_make_alter_car_model_alter_car_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='brokers.broker'),
        ),
        migrations.AddField(
            model_name='car',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dealers.dealer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('commission', 'Commission'), ('purchase', 'Purchase'), ('verification_fee', 'Verification Fee')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(('dealer__isnull', False), ('broker__isnull', False), _connector='OR'), name='dealer_or_broker_required'),
        ),
    ]
