# Generated by Django 5.2.5 on 2025-09-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_carview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
