# Generated by Django 5.2.5 on 2025-09-22 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='carview',
            constraint=models.UniqueConstraint(fields=('car', 'user'), name='unique_car_user_view'),
        ),
    ]
