# Generated by Django 5.2.5 on 2025-11-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True),
        ),
    ]
