# Generated by Django 5.2.5 on 2025-12-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_car_origin_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='priority',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]
