# Generated by Django 5.2.5 on 2025-12-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_car_created_at_alter_car_mileage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
