# Generated by Django 5.2.5 on 2025-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_carmodel_options_alter_carmake_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
