# Generated by Django 5.2.5 on 2026-01-26 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_car_sold_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carview',
            name='unique_car_user_view',
        ),
        migrations.AddIndex(
            model_name='carview',
            index=models.Index(fields=['viewed_at'], name='inventory_c_viewed__50cef9_idx'),
        ),
        migrations.AddIndex(
            model_name='carview',
            index=models.Index(fields=['car', 'viewed_at'], name='inventory_c_car_id_0ca96e_idx'),
        ),
        migrations.AddIndex(
            model_name='carview',
            index=models.Index(fields=['user'], name='inventory_c_user_id_be06e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='carview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('car', 'user'), name='unique_car_user_view'),
        ),
        migrations.AddConstraint(
            model_name='carview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('car', 'ip_address'), name='unique_car_ip_view'),
        ),
    ]
