# Generated by Django 5.2.5 on 2026-02-14 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_remove_brokerprofile_idx_brokerprofile_profile_and_more'),
        ('dealers', '0007_dealerprofile_rejection_reason_and_more'),
        ('inventory', '0013_remove_carview_unique_car_user_view_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='car',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='verified_by',
        ),
        migrations.RemoveConstraint(
            model_name='car',
            name='dealer_or_broker_required',
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('broker__isnull', True), ('dealer__isnull', False)), models.Q(('broker__isnull', False), ('dealer__isnull', True)), _connector='OR'), name='exactly_one_of_dealer_or_broker'),
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
