# Generated by Django 5.2.5 on 2026-01-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('employee', 'component')},
        ),
    ]
