# Generated by Django 5.2.5 on 2026-02-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payrollitem',
            table='payroll_payrollitem',
        ),
        migrations.AlterModelTable(
            name='payrollline',
            table='payroll_payrollline',
        ),
        migrations.AlterModelTable(
            name='payrollrun',
            table='payroll_payrollrun',
        ),
    ]
