# Generated by Django 5.2.5 on 2026-01-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employeesalary_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollitem',
            unique_together={('payroll_run', 'employee')},
        ),
    ]
