# Generated by Django 5.2.5 on 2026-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrollitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='payrollitem',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payroll_item_per_employee'),
        ),
    ]
