# Generated by Django 5.2.5 on 2026-01-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payrollitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('period',), name='unique_payroll_per_period'),
        ),
    ]
