# Generated by Django 5.2.5 on 2026-02-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollrun_unique_payroll_per_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type', models.CharField(choices=[('1.5', 'Normal Overtime (1.5x)'), ('1.75', 'Weekend Overtime (1.75x)'), ('2.0', 'Special Overtime (2.0x)'), ('2.5', 'Holiday Overtime (2.5x)')], max_length=4)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollrun')),
            ],
        ),
    ]
