# Generated by Django 5.2.5 on 2026-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('broker', 'Broker'), ('dealer', 'Dealer'), ('admin', 'Admin')], default='buyer', max_length=20),
        ),
    ]
