# Generated by Django 5.2.5 on 2026-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('broker', 'Broker'), ('dealer', 'Dealer'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='buyer', max_length=20),
        ),
    ]
