# Generated by Django 5.2.5 on 2026-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('broker', 'Broker'), ('dealer', 'Dealer'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('inspector', 'Inspector')], default='buyer', max_length=20),
        ),
    ]
