# Generated by Django 5.2.5 on 2026-03-11 07:12

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_by', models.CharField(help_text='Garage or company that inspected the car', max_length=255)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, help_text='Summary of inspection result')),
                ('condition_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=50)),
                ('report_document', cloudinary.models.CloudinaryField(blank=True, help_text='Upload the scanned inspection report (PDF or photo)', max_length=255, null=True, verbose_name='inspection_report')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, help_text='Remarks by admin during verification')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car Inspection',
                'verbose_name_plural': 'Car Inspections',
            },
        ),
    ]
