# Generated by Django 5.2.5 on 2026-03-11 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='car',
            field=models.OneToOneField(help_text='Car being inspected', on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='inventory.car'),
        ),
    ]
