# Generated by Django 5.2.5 on 2026-06-14 09:45

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_initial'),
        ('inventory', '0005_add_views_count_to_car'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-inspection_date']},
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspected_by',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='report_document',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='inspection',
            name='accident_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='odometer_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='signed_report',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='signed_report'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='admin_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inventory.car'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='condition_status',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspectors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspection.inspector'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['car'], name='inspection__car_id_f779c4_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspector'], name='inspection__inspect_759d45_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='inspection__status_059dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspection_date'], name='inspection__inspect_f2b6da_idx'),
        ),
    ]
