# Generated by Django 5.2.5 on 2025-09-13 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='dealerrating',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dealers.dealerprofile'),
        ),
        migrations.AddField(
            model_name='dealerrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dealerprofile',
            index=models.Index(fields=['profile'], name='idx_dealerprofile_profile'),
        ),
        migrations.AddIndex(
            model_name='dealerrating',
            index=models.Index(fields=['dealer'], name='idx_dealerrating_dealer'),
        ),
        migrations.AddIndex(
            model_name='dealerrating',
            index=models.Index(fields=['user'], name='idx_dealerrating_user'),
        ),
        migrations.AddIndex(
            model_name='dealerrating',
            index=models.Index(fields=['dealer', 'user'], name='idx_dealerrating_dealer_user'),
        ),
        migrations.AddConstraint(
            model_name='dealerrating',
            constraint=models.UniqueConstraint(fields=('dealer', 'user'), name='unique_dealer_user_rating'),
        ),
        migrations.AddConstraint(
            model_name='dealerrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='dealerrating_valid_range'),
        ),
    ]
