# Generated by Django 5.2.5 on 2025-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
