# Generated by Django 5.2.5 on 2026-06-01 19:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='business_license',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='business_license'),
        ),
    ]
