# Generated by Django 5.2.5 on 2025-10-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealerstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerstaff',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('accountant', 'Accountant')], max_length=20),
        ),
    ]
