# Generated by Django 5.2.5 on 2025-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealer_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
