# Generated by Django 5.2.5 on 2026-06-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealerprofile_business_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
