# Generated by Django 5.2.5 on 2025-08-28 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_rename_name_dealer_company_name_dealer_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='company_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='DealerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dealers.dealer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['dealer'], name='idx_dealerrating_dealer'), models.Index(fields=['user'], name='idx_dealerrating_user'), models.Index(fields=['dealer', 'user'], name='idx_dealerrating_dealer_user')],
                'constraints': [models.UniqueConstraint(fields=('dealer', 'user'), name='unique_dealer_user_rating'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='dealerrating_valid_range')],
            },
        ),
    ]
