# Generated by Django 5.2.5 on 2025-10-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_alter_dealerstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerstaff',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('accountant', 'Accountant'), ('hr', 'HR')], max_length=20),
        ),
    ]
