# Generated by Django 5.2.5 on 2026-02-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_alter_dealerstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerstaff',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('accountant', 'Accountant'), ('hr', 'HR'), ('finance', 'Finance')], max_length=20),
        ),
    ]
