# Generated by Django 5.2.5 on 2026-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
