# Generated by Django 5.2.5 on 2025-09-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delete_payment'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car'),
        ),
    ]
