# Generated by Django 5.2.5 on 2025-10-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_alter_dealerstaff_role'),
        ('sales', '0003_lead_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dealers.dealerprofile'),
        ),
    ]
