# Generated by Django 5.2.5 on 2026-02-14 21:31

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_inspection_car_remove_inspection_uploaded_by_and_more'),
        ('sales', '0005_lead_buyer_alter_lead_assigned_sales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='inventory.car'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('contacted', 'Contacted'), ('negotiation', 'Negotiation'), ('closed', 'Closed'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('contact'), models.F('car'), name='unique_lead_contact_per_car_ci'),
        ),
    ]
