# Generated by Django 5.2.5 on 2025-10-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('dealers', '0004_alter_dealerstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dealers.dealerprofile'),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='dealers.dealerprofile'),
        ),
    ]
