# Generated by Django 5.2.5 on 2025-10-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_exchangerate_expense_currency_expense_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('shipping', 'Shipping'), ('tax', 'Tax'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('salary', 'Salary'), ('operational', 'Operational'), ('other', 'Other')], max_length=100),
        ),
    ]
