# Generated by Django 5.2.5 on 2025-10-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_expense_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='date',
            new_name='created_at',
        ),
    ]
