# Generated by Django 5.2.5 on 2025-10-27 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_rename_date_revenue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
