# Generated by Django 5.2.5 on 2025-12-04 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_expense_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='carexpense',
            name='date',
        ),
        migrations.AddField(
            model_name='carexpense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
