# Generated by Django 5.2.5 on 2025-12-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_expense_dealer_expense_company_and_more'),
        ('dealers', '0005_alter_dealerstaff_role'),
        ('inventory', '0011_alter_carmodel_options_alter_carmake_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carexpense',
            old_name='dealer',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='carexpense',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_expenses', to='inventory.car'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='dealers.dealerprofile'),
        ),
    ]
