# Generated by Django 5.2.5 on 2026-01-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_carexpense_declaration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carexpense',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
