# Generated by Django 5.2.5 on 2026-03-11 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('permanent', 'Permanent'), ('probation', 'Probation (60 days)'), ('temporary', 'Temporary / Contract'), ('intern', 'Intern')], default='probation', help_text='Type of employment contract', max_length=20)),
                ('job_title', models.CharField(max_length=150)),
                ('contract_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='For temporary contracts', null=True)),
                ('terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_employee', 'Sent to Employee'), ('signed_by_employee', 'Signed by Employee'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=25)),
                ('draft_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('employee_signed_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('final_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('employee_signed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'payroll_employeesalary',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
            },
        ),
        migrations.CreateModel(
            name='OvertimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type', models.CharField(choices=[('1.5', 'Normal Overtime (1.5x)'), ('1.75', 'Weekend Overtime (1.75x)'), ('2.0', 'Special Overtime (2.0x)'), ('2.5', 'Holiday Overtime (2.5x)')], max_length=4)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'payroll_overtimeentry',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=10)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_pensionable', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payroll_salarycomponent',
            },
        ),
    ]
