# Generated by Django 5.2.5 on 2025-11-09 10:28

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='salary',
            new_name='contract_salary',
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload scanned signed contract (PDF or photo)', max_length=255, null=True, verbose_name='contract_document'),
        ),
        migrations.AddField(
            model_name='contract',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
