# Generated by Django 5.2.5 on 2026-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimeentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='employeesalary',
            table='payroll_employeesalary',
        ),
        migrations.AlterModelTable(
            name='overtimeentry',
            table='payroll_overtimeentry',
        ),
        migrations.AlterModelTable(
            name='salarycomponent',
            table='payroll_salarycomponent',
        ),
    ]
