# Generated by Django 5.2.5 on 2026-02-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeesalary',
            table='payroll_employeesalary',
        ),
        migrations.AlterModelTable(
            name='overtimeentry',
            table='payroll_overtimeentry',
        ),
        migrations.AlterModelTable(
            name='salarycomponent',
            table='payroll_salarycomponent',
        ),
    ]
