# Generated by Django 5.2.5 on 2025-11-12 10:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_rename_salary_contract_contract_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='document',
        ),
        migrations.AddField(
            model_name='contract',
            name='company_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/stamps/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee_signature',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/signatures/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hr_signature',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/hr_signatures/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='signed_contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20),
        ),
    ]
