# Generated by Django 5.2.5 on 2025-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='draft_document',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employee_signed_document',
        ),
        migrations.AddField(
            model_name='contract',
            name='draft_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee_signed_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='final_document_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
