# Generated by Django 5.2.5 on 2026-02-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employeesalary_table_alter_overtimeentry_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeentry',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
