# Generated by Django 5.2.5 on 2025-11-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_contract_draft_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='final_document',
        ),
    ]
