# Generated by Django 5.2.5 on 2026-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_fix_overtimeentry_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimeentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
