# Generated by Django 5.2.5 on 2025-09-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to='users.profile'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='buyers.buyerprofile'),
        ),
        migrations.AddIndex(
            model_name='buyerprofile',
            index=models.Index(fields=['profile'], name='idx_buyerprofile_profile'),
        ),
    ]
