# Generated by Django 5.2.5 on 2025-08-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
